### ISSUE TITLE
About us

### ISSUE THREAD

**Issue by simi** [zizkovrb/zizkovrb.org#4]
@pepe @pajasevi @papricek please copy and fill this for about us page (if you want to be there):

```
| column        | value |
|---------------|-------|
| nick          |       |
| name          |       |
| rank          |       |
| avatar        |       |
| occupation    |       |
| github        |       |
| twitter       |       |
| another links |       |
| about me      |       |
```

**Comment by simi** [comment]
My WIP

| column          | value                                                                      |
|---------------|----------------------------------------------------------------------------------|
| nick          | retro, simi                                                                      |
| name          | Josef Šimánek                                                                    |
| rank          |                                                                                  |
| avatar        | http://www.gravatar.com/avatar/e15b6dce2c0548cdec19b09a7d183917.jpg              |
| occupation    | Deli clerk                                                                       |
| github        | @simi                                                                            |
| twitter       | https://twitter.com/retrorubies                                                  |
| another links | https://rubygems.org/profiles/retro, http://stackoverflow.com/users/319233/retro |
| about me      |                                                                                  |

**Comment by pepe** [comment]
| column        | value |
|---------------|-------|
| nick          |    pepe   |
| name          |    Josef Pospíšil   |
| rank          |   Colonel    |
| avatar        |   https://avatars3.githubusercontent.com/u/3204?v=3&s=460    |
| occupation    |   Master of none, slave of all     |
| github        |    @pepe   |
| twitter       |   https://twitter.com/damnpepe    |
| another links |       |
| about me      |   First Rubyist in the Czech Republic and last star around.    |

**Comment by pepe** [comment]
stačí takto?

**Comment by simi** [comment]
:+1:

**Comment by pajasevi** [comment]
| column        | value |
|---------------|-------|
| nick          | pajasevi, piql  |
| name          | Pavel Ševčík |
| rank          | Second lieutenant |
| avatar        | https://avatars2.githubusercontent.com/u/2407408?v=3&s=460 |
| occupation    | Love lover, hate lover |
| github        |    https://github.com/pajasevi   |
| twitter       |  https://twitter.com/pajasevi     |
| another links |       |
| about me      |    I code. That's about it.   |

**Comment by papricek** [comment]
| column          | value                                                                      |
|---------------|----------------------------------------------------------------------------------|
| nick          | papricek                                                                      |
| name          | Patrik Jíra                                                                    |
| rank          | Captain                                                                       |
| avatar        | http://gravatar.com/avatar/b04a553de1b8b45433b841bba440cc42              |
| occupation    | Supply officer                                                                        |
| github        | @simi                                                                            |
| twitter       | https://twitter.com/papricek                                                  |
| another links |  |
| about me      |                                                                                  |
